## Atividade Módulo 02

Questão 01

Associe o comando em python ao seu significado:

matriz = np.array([[1, 2, 3], [2, 4, 6], [7, 8, 9], [3, 6, 9]])
	
matriz = np.zeros( (4, 3) )

matriz = np.empty( (4, 3) )



In [2]:

import numpy as np
matriz = np.zeros((4,3))

print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Questão 02
Associe o comando em python ao seu significado:

meuVetor = np.array([1,2,4,6,8,10])

meuVetor = np.empty (6)

meuVetor = np.zeros (6)

In [3]:
ve = np.empty(6)
print(ve)

[-1.52975647e-311  1.52975647e-311  0.00000000e+000  0.00000000e+000
  0.00000000e+000  0.00000000e+000]


In [4]:
arr = "Python is fun"
for i in range(0, 13, 2):
     print(arr[i], end = "")

Pto sfn

In [5]:
def f(x):
     return x ** 2

arr1 = np.array([1, 2, 3])
arr2 = f(arr1)
print(arr2)

[1 4 9]
